name: Auto Post Deals to Blogger

on:
  schedule:
    - cron: '0 */6 * * *'  # Runs every 6 hours
  workflow_dispatch:  # Allows manual triggering

jobs:
  post_to_blogger:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        - run: pip install requests google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client


      - name: Run Blogger Script
        env:
          BLOG_ID: ${{ secrets.SECRET_BLOGGER_BLOG_ID }}
          CLIENT_ID: ${{ secrets.SECRET_BLOGGER_CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.SECRET_BLOGGER_CLIENT_SECRET }}
          REFRESH_TOKEN: ${{ secrets.SECRET_BLOGGER_REFRESH_TOKEN }}
        run: python post_to_blogger.py
