name: Auto Post Deals to Blogger

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"  # Runs every hour
  workflow_dispatch:  # Allows manual triggering

jobs:
  post_to_blogger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: pip install requests google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Run Blogger Post Script
        env:
          SECRET_BLOGGER_BLOG_ID: ${{ secrets.SECRET_BLOGGER_BLOG_ID }}
          SECRET_BLOGGER_CLIENT_ID: ${{ secrets.SECRET_BLOGGER_CLIENT_ID }}
          SECRET_BLOGGER_CLIENT_SECRET: ${{ secrets.SECRET_BLOGGER_CLIENT_SECRET }}
          SECRET_BLOGGER_REFRESH_TOKEN: ${{ secrets.SECRET_BLOGGER_REFRESH_TOKEN }}
        run: python post_to_blogger.py
